server:
  port: 8111



baiduParameter:
  url: http://api.map.baidu.com/geocoder/v2/
  ak: 4SfCKOolPLPlEljQPT3rNG4yl3G33CR7



spring:
  datasource:
    url: jdbc:mysql://rm-bp1m8pq407s2yls07o.mysql.rds.aliyuncs.com:3306/inner_db?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: select 1


local:
  datasource:
    url: jdbc:mysql://localhost:3306/address?failOverReadOnly=false&useUnicode=true&characterEncoding=utf-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: test
    password: test
    max-active: 50
    min-idle: 10
    max-idle: 10
    initial-size: 15
    max-wait: 5
    test-on-borrow: true
    validation-query: select 1



